DROP DATABASE IF EXISTS profiles_db;
CREATE DATABASE exceptional_profiles;
USE exceptional_profiles;

DROP TABLE IF EXISTS profiles;

CREATE TABLE IF NOT EXISTS profiles (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name  VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE
);